#!/usr/bin/env python3
"""Generate src/render/colormaps.ts: 256-entry RGB lookup tables for the
colormaps the Display panel offers, sampled from matplotlib exactly like
the legacy backend's GeoTIFF palette was (plt.get_cmap(name, 256)).

Usage: python3 scripts/gen_colormap_luts.py
"""

import os

import matplotlib

matplotlib.use("Agg")
import matplotlib.pyplot as plt
import numpy as np

# Keep in sync with the options in src/components/Display.vue.
COLORMAPS = ["plasma", "CMRmap", "cool", "viridis", "turbo", "jet"]

REPO = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
OUT = os.path.join(REPO, "src", "render", "colormaps.ts")


def lut_hex(name: str) -> str:
    cmap = plt.get_cmap(name, 256)
    rgb = (cmap(np.linspace(0.0, 1.0, 256))[:, :3] * 255).astype(int)
    return "".join(f"{r:02x}{g:02x}{b:02x}" for r, g, b in rgb)


def main() -> None:
    entries = ",\n".join(
        f"  {name}:\n    '{lut_hex(name)}'" for name in COLORMAPS
    )
    content = f"""/* GENERATED by scripts/gen_colormap_luts.py - do not edit by hand.
 * 256-entry RGB lookup tables sampled from matplotlib, matching the
 * palettes the legacy backend baked into its GeoTIFFs. */

const HEX_LUTS: Record<string, string> = {{
{entries},
}};

const decoded = new Map<string, Uint8Array>();

export const COLORMAP_NAMES = Object.keys(HEX_LUTS);

/** 256*3 RGB bytes for a colormap; falls back to plasma. */
export function colormapLut(name: string): Uint8Array {{
  const key = name in HEX_LUTS ? name : 'plasma';
  let lut = decoded.get(key);
  if (!lut) {{
    const hex = HEX_LUTS[key];
    lut = new Uint8Array(768);
    for (let i = 0; i < 768; i++)
      lut[i] = parseInt(hex.slice(i * 2, i * 2 + 2), 16);
    decoded.set(key, lut);
  }}
  return lut;
}}
"""
    with open(OUT, "w") as f:
        f.write(content)
    print(f"wrote {OUT} ({len(COLORMAPS)} colormaps)")


if __name__ == "__main__":
    main()
